# Generated by Django 4.2.5 on 2023-09-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='movie_table',
        ),
    ]
